name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📝 Commit Message Format
        
        When implementing this feature, please use conventional commit format:
        
        ```
        feat: brief description of the feature
        
        Closes #<issue-number>
        ```
        
        **Examples:**
        - `feat: add book search by ISBN`
        - `feat: implement user preference settings`
        - `feat(api): add pagination to book list endpoint`
        
        **For breaking changes:**
        ```
        feat: redesign authentication system
        
        BREAKING CHANGE: Old JWT tokens are no longer valid.
        Users must re-authenticate.
        
        Closes #<issue-number>
        ```
        
        This helps us automatically generate changelogs and version releases!
        
        Learn more: [Conventional Commits](https://www.conventionalcommits.org/)
